# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apitaxapresentation:
    image: apitaxapresentation
    container_name: apitaxa
    build:
      context: ./ApiTaxa
      dockerfile: Dockerfile
    ports:
      - "3001:80"

  presentation:
    image: presentation
    container_name: apicalculajuros
    build:
      context: ./ApiCalculaJuros
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - apitaxapresentation
